apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.3
        profile:
            VendorType: redhat
            version: v1.2
        reportDigest: uint64:9399389562103538660
        chart-uri: /workspace/tmp/charts/redhat-trusted-application-pipeline-0.1.0.tgz
        digests:
            chart: sha256:4e9326e2079cece33c0acc51dfe907303bb1b386d4cc0cc39f74809b3e927c9d
            package: 2c2ebbf5cd076f7eaf0f2f9d5d75b48caaddffe8512373328ef87bc1ca7a3031
        lastCertifiedTimestamp: "2024-04-05T20:42:04.146428+00:00"
        testedOpenShiftVersion: "4.14"
        supportedOpenShiftVersions: '>=4.12'
        webCatalogOnly: false
    chart:
        name: redhat-trusted-application-pipeline
        home: ""
        sources:
            - https://github.com/redhat-appstudio/rhtap-installer
        version: 0.1.0
        description: A Helm chart for deploying Red Hat Trusted Application Pipeline
        keywords: []
        maintainers:
            - name: Red Hat Trusted Application Pipeline Team
              email: ""
              url: https://github.com/redhat-appstudio/rhtap-installer
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.1.0
        deprecated: false
        annotations:
            charts.openshift.io/name: Trusted Application Pipeline
            charts.openshift.io/provider: Red Hat
            charts.openshift.io/supportURL: https://github.com/redhat-appstudio/rhtap-installer/issues
        kubeversion: '>= 1.25.0-0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: No images to certify
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: FAIL
      reason: Values schema file does not exist
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified

