name: Build and Verify

on:
  pull_request_target: {}

jobs:
  valid-user:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Verify PR
        id: verifypr
        continue-on-error: true
        run: |
          gpg --version
          python3 -m venv ve1
          cd scripts && ../ve1/bin/python3 setup.py install && cd ..
          ve1/bin/chart-pr-review --verify-user=${{ github.actor }} --pr-number=${{ github.event.number }}

      - name: "Comment pr review error [1]"
        if: steps.verifypr.conclusion != 'failure'
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            PR review has been failed with an error. ${{ steps.verifypr.conclusion }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: true # This is the default
