name: Sanity Check

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  sanity-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Sanity Check PR Content
        id: sanity_check_pr_content
        continue-on-error: true
        run: |
          python3 -m venv ve1
          cd scripts && ../ve1/bin/pip3 install -r requirements.txt && cd ..
          cd scripts && ../ve1/bin/python3 setup.py install && cd ..
          ./ve1/bin/sanity-check-pr --api-url=${{ github.event.pull_request._links.self.href }}

      - uses: actions/github-script@v3
        if: ${{ steps.sanity_check_pr_content.outcome == 'success'}}
        continue-on-error: true
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['sanity-ok']
            })

      - uses: actions/github-script@v3
        if: ${{ steps.sanity_check_pr_content.outcome == 'failure'}}
        continue-on-error: true
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'sanity-ok'
            })

      - uses: actions/github-script@v3
        if: ${{ always() && steps.sanity_check_pr_content.outcome == 'success'}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for the PR!  The sanity check has been a success. Please wait for the test result.'
            })

      - uses: actions/github-script@v3
        if: ${{ always() && steps.sanity_check_pr_content.outcome == 'failure'}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for the PR!  The sanity check has been a failure. Please ensure only chart related files have been modified.'
            })

      - name: Reflect on Sanity Check PR Content
        if: ${{ always() && steps.sanity_check_pr_content.outcome == 'failure'}}
        run: |
          echo "The 'Sanity Check PR Content' step has failed."
          exit 1
